190410_BlogV1/Models/Makaleler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _190410_BlogV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makaleler
    {
        public int MakalelerID { get; set; }
        public string Baslik { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<int> GoruntulenmeSayisi { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
        public Nullable<int> BegenmeSayisi { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<bool> Aktifmi { get; set; }
    }
}

190410_BlogV1/Controllers/MakalelerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _190410_BlogV1.Controllers
{
    public class MakalelerController : Controller
    {
        //*****************************************************************
        Models.Bloghi304DBEntities1 db = new Models.Bloghi304DBEntities1();
        // GET: Makaleler
        public ActionResult MakaleListesiIndex()
        {
            return View();
        }

        public ActionResult MakaleDetayIndex(int id)
        {
            //var makaleId = RouteData.Values["id"];
            var makaleDetay = db.Makaleler.Where(m => m.MakalelerID == id).FirstOrDefault();

            ViewBag.Yazar = db.Uyeler.Where(y => y.UyelerID == makaleDetay.YazarID && y.Yazarmi == true).FirstOrDefault().Adi;
            //ViewBag.Resim = DB.Resimler.Where(r => r.MakaleID == id).FirstOrDefault().BuyukBoyut;
            return View(makaleDetay);
        }

        public ActionResult YorumListesi(int id)
        {
            var Yorumlar = db.Yorumlar.Where(k => k.MakaleID == id).ToList();
            return View(Yorumlar);
        }

        public ActionResult KategoriListeiIndex()
        {
            return View();
        }

        public ActionResult KategoriListesi()
        {

            return View(db.Kategoriler.ToList());
        }
    }
}

190410_BlogV1/Views/Makaleler/KategoriListesi.cshtml
@model List<Kategoriler>



<div class="categories">
    <h4>KATEGORİLER</h4>
    @*<h6><a href="#">Vivamus vestibulum nulla</a></h6>*@
    @foreach (var item in Model)
        {
            <h6>
        <a href="#">@item.KategoriAdi</a>
            </h6>
        }   
</div>

190410_BlogV1/Views/Makaleler/MakaleDetayIndex.cshtml
@model _190410_BlogV1.Models.Makaleler
@{
    ViewBag.Title = "MakaleDetayIndex";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<div class="details">
    <div class="container">
        <div class="det_pic">
            <img src="~/Template/images/img18.jpg" class="img-responsive" alt="">
        </div>
        <div class="det_text">
            <h2>@Model.Baslik </h2>
            <p>@Model.icerik</p>
        </div>
        <ul class="links">
            <li><i class="date"> </i><span class="icon_text">@Model.EklenmeTarihi</span></li>
            <li><a href="#"><i class="admin"> </i><span class="icon_text"> @ViewBag.Yazar </span></a></li>
            <li class="last"><a href="#"><i class="permalink"> </i><span class="icon_text">Permalink</span></a></li>
        </ul>
        <ul class="links_middle">
            <li><i class="date"> </i><span class="icon_text">@Model.GuncellenmeTarihi</span></li>
            <li><i class="tags"> </i><span class="icon_text">Etiketler</span></li>
        </ul>
        <ul class="links_bottom">
            <li><a href="#"><i class="comments"> </i><span class="icon_text">5 Comments</span></a></li>
            <li><i class="views"> </i><span class="icon_text">@Model.GoruntulenmeSayisi</span></li>
            <li><i class="likes"> </i><span class="icon_text">@Model.BegenmeSayisi</span></li>
        </ul>

        <!----------------------------------yorum listesi-------------------------------------------->
        <div class="comments1">
            <h4>YORUMLAR</h4>

            @Html.Action("YorumListesi", "Makaleler")

        </div>
        <!----------------------------------yorum listesi-------------------------------------------->
        <div class="lev">
            <div class="leave">
                <h4>Yorum Yapın</h4>
            </div>
            <form id="commentform">
                <label for="author">İsim</label>
                <input id="author" name="author" type="text" value="" size="30" aria-required="true">
                <label for="email">Email</label>
                <input id="email" name="email" type="text" value="" size="30" aria-required="true">
                <label for="url">Yorum Başlık</label>
                <input id="url" name="url" type="text" value="" size="30">
                <label for="comment">Yorum</label>
                <textarea></textarea>
                <div class="clearfix"></div>
                <input name="submit" type="submit" id="submit" value="Paylaş">
                <div class="clearfix"></div>
            </form>
        </div>

    </div>
</div>

190410_BlogV1/Views/Makaleler/YorumListesi.cshtml
@model List<_190410_BlogV1.Models.Yorumlar>

@foreach (var item in Model)
{
    <div class="comments-main">
        <div class="col-md-2 cmts-main-left">
            <img src="~/Template/images/avatar.png" alt="">
        </div>
        <div class="col-md-10 cmts-main-right">
            <h5>@item.YorumBaslik</h5>
            <p>@item.Yorumicerik</p>
            <div class="cmts">
                <div class="cmnts-left">
                    <p>@item.YorumTarihi</p>
                </div>
                <div class="cmnts-right">
                    <a href="#">Reply</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
}